Scryvex Pro V2 2.2.3 - S6-rc Bootfix

diff --git a/addon/rootfs/usr/local/bin/scryvex-postgres-setup b/addon/rootfs/usr/local/bin/scryvex-postgres-setup
--- a/addon/rootfs/usr/local/bin/scryvex-postgres-setup
+++ b/addon/rootfs/usr/local/bin/scryvex-postgres-setup
@@ -1,5 +1,6 @@
 #!/command/with-contenv bash
-set -Eeuo pipefail
+set -Eeuxo pipefail
+trap 'rc=$?; echo "[postgres-setup] ERROR rc=$rc line=$LINENO command=$BASH_COMMAND" >&2' ERR
 
 echo "[postgres-setup] Esperando PostgreSQL..."
 
